### ISSUE TITLE
Issue with typeclasses having more than one generic/typeclass parameter.

### ISSUE THREAD

**Issue by alexd6631** [arrow-kt/kotlin#13]
Hello and thanks a lot for the hard work on Arrow and making possible to use typeclasses with Kotlin !

I am encoutering a compiler error when trying to implement a Monoid of a Kotlin pair using the following code :

Typeclasses declarations & instances
```kotlin
package test.keep87.typeclasses

import test.keep87.Wrapper

interface Monoid<A> {
    fun empty(): A
    fun A.combine(other: A): A

    companion object {
        extension class IntMonoid : Monoid<Int> {
            override fun empty(): Int = 0
            override fun Int.combine(other: Int): Int = this + other
        }

        extension class StringMonoid : Monoid<String> {
            override fun empty(): String = ""
            override fun String.combine(other: String) = this + other
        }

        extension class PairMonoid<A, B>(
            with val aMonoid: Monoid<A>,
            with val bMonoid: Monoid<B>
        ) : Monoid<Pair<A, B>> {
            override fun Pair<A, B>.combine(other: Pair<A, B>): Pair<A, B> =
                first.combine(other.first) to second.combine(other.second)

            override fun empty() = aMonoid.empty() to bMonoid.empty()
        }

        extension class WrapperMonoid<A>(with val monoid: Monoid<A>) : Monoid<Wrapper<A>> {
            override fun empty(): Wrapper<A> = Wrapper(monoid.empty())

            override fun Wrapper<A>.combine(other: Wrapper<A>): Wrapper<A> =
                Wrapper(value.combine(other.value))
        }
    }
}
```

Sample code
```kotlin
package test.keep87

import test.keep87.typeclasses.Monoid

fun <A> naturalMultiply(a: A, n: Int, with monoid: Monoid<A>): A {
    var acc = monoid.empty()
    for (i in 1..n) { acc = acc.combine(a) }
    return acc
}

data class Wrapper<A>(val value: A)

fun main(args: Array<String>) {
    println(naturalMultiply(42 to "42", 10))
}
```

I have no issue with Wrapper monoid, but trying to resolve the Pair monoid gives the following error :

```
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: wrong code generated
org.jetbrains.kotlin.codegen.CompilationException Back-end (JVM) Internal error: Couldn't transform method node:
main ([Ljava/lang/String;)V:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
Element is unknownThe root cause was thrown at: MethodAnalyzer.kt:150
bytecode:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Back-end (JVM) Internal error: Couldn't transform method node:
main ([Ljava/lang/String;)V:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
Element is unknownThe root cause was thrown at: MethodAnalyzer.kt:150
File being compiled at position: (13,1) in /Users/alexandre/Development/Tests/TestTypeclassesKeep87/src/test/keep87/Test.kt
The root cause was thrown at: TransformationMethodVisitor.java:88
File being compiled at position: file:///Users/alexandre/Development/Tests/TestTypeclassesKeep87/src/test/keep87/Test.kt
The root cause was thrown at: FunctionCodegen.java:1033
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:446)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:142)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:435)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1020)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1062)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1019)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:433)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong code generated
org.jetbrains.kotlin.codegen.CompilationException Back-end (JVM) Internal error: Couldn't transform method node:
main ([Ljava/lang/String;)V:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
Element is unknownThe root cause was thrown at: MethodAnalyzer.kt:150
bytecode:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Back-end (JVM) Internal error: Couldn't transform method node:
main ([Ljava/lang/String;)V:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
Element is unknownThe root cause was thrown at: MethodAnalyzer.kt:150
File being compiled at position: (13,1) in /Users/alexandre/Development/Tests/TestTypeclassesKeep87/src/test/keep87/Test.kt
The root cause was thrown at: TransformationMethodVisitor.java:88
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:1033)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:449)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:266)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:183)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:154)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:196)
	at org.jetbrains.kotlin.codegen.PackagePartCodegen.generateBody(PackagePartCodegen.java:95)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:128)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:127)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	... 35 more
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
main ([Ljava/lang/String;)V:
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 0
    LDC "args"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 14 L1
    BIPUSH 42
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    LDC "42"
    INVOKESTATIC kotlin/TuplesKt.to (Ljava/lang/Object;Ljava/lang/Object;)Lkotlin/Pair;
    BIPUSH 10
    NEW test/keep87/typeclasses/Monoid$Companion$PairMonoid
    DUP
    NEW test/keep87/typeclasses/Monoid$Companion$IntMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$IntMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    NEW test/keep87/typeclasses/Monoid$Companion$StringMonoid
    DUP
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$StringMonoid.<init> ()V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V
    CHECKCAST test/keep87/typeclasses/Monoid
    INVOKESTATIC test/keep87/TestKt.naturalMultiply (Ljava/lang/Object;ILtest/keep87/typeclasses/Monoid;)Ljava/lang/Object;
    ASTORE 1
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.beforeInlineCall ()V
    NOP
   L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/Object;)V
   L3
    NOP
    GOTO L4
   L4
    INVOKESTATIC kotlin/jvm/internal/InlineMarker.afterInlineCall ()V
   L5
    LINENUMBER 15 L5
    RETURN
   L6
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    MAXSTACK = 7
    MAXLOCALS = 2
Cause: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
Element is unknownThe root cause was thrown at: MethodAnalyzer.kt:150
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:88)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:1021)
	... 44 more
Caused by: org.jetbrains.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction #21 INVOKESPECIAL test/keep87/typeclasses/Monoid$Companion$PairMonoid.<init> (Ltest/keep87/typeclasses/Monoid;, Ltest/keep87/typeclasses/Monoid;)V: null
	at org.jetbrains.kotlin.codegen.optimization.common.MethodAnalyzer.analyze(MethodAnalyzer.kt:150)
	at org.jetbrains.kotlin.codegen.optimization.fixStack.FixStackAnalyzer.analyze(FixStackAnalyzer.kt:60)
	at org.jetbrains.kotlin.codegen.optimization.fixStack.FixStackMethodTransformer.analyzeAndTransformBreakContinueGotos(FixStackMethodTransformer.kt:55)
	at org.jetbrains.kotlin.codegen.optimization.fixStack.FixStackMethodTransformer.transform(FixStackMethodTransformer.kt:44)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:25)
	at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.kt:62)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:65)
	... 45 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

Best regards

**Comment by truizlop** [comment]
Thanks @alexd6631 for your nice words and for helping us test the implementation of KEEP-87. The error you are pointing is something that I haven't still tried. I think it is probably due to an implementation with two type parameters. So far I've been focusing on just one. I'll take a look and address your case.

**Comment by pakoito** [comment]
One way we could resolve this is by having all typeclasses reeive multiple parameters, and rewrite them to use some helpers like `ComposedGeneric4<A, B, C, D>`.

For example, some Haskell automatic derivation doesn't get past arities of 16: https://twitter.com/chris__martin/status/1064961635910123523, https://twitter.com/chris__martin/status/1064963485610708994
