### ISSUE TITLE
Exception during code generation: Unable to resolve implicit parameter

### ISSUE THREAD

**Issue by hannespernpeintner** [arrow-kt/kotlin#8]
This example works as expected:
```
interface Semigroup<A> {
    fun A.combine(b: A): A
}
extension class IntSemigroup: Semigroup<Int> {
    override fun Int.combine(b: Int): Int {
        return this + b
    }
}
fun add(a: Int, b: Int, with semigroup: Semigroup<Int>): Int {
    return a.combine(b)
}
fun main(args: Array<String>) {
    println(add(1,2)) // outputs 3
}
```

As soon as I change the signature of fun add to
```
fun add(a: Int, b: Int, with semigroup: IntSemigroup): Int
```
I got the following compilation error:

> Error:Kotlin: [Internal Error] java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Failed to generate function main
Cause: Unable to resolve implicit parameter semigroup: IntSemigroup
File being compiled at position: (34,1) in /home/tenter/IdeaProjects/keep87/src/Main.kt
The root cause was thrown at: CallBasedArgumentGenerator.java:107
File being compiled at position: file:///home/tenter/IdeaProjects/keep87/src/Main.kt
The root cause was thrown at: MemberCodegen.java:202
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:446)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:142)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:435)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$1.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1020)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1062)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1019)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:433)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate function main
Cause: Unable to resolve implicit parameter semigroup: IntSemigroup
File being compiled at position: (34,1) in /home/tenter/IdeaProjects/keep87/src/Main.kt
The root cause was thrown at: CallBasedArgumentGenerator.java:107
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:202)
	at org.jetbrains.kotlin.codegen.PackagePartCodegen.generateBody(PackagePartCodegen.java:95)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:128)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:127)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	... 35 more
Caused by: java.lang.IllegalStateException: Unable to resolve implicit parameter semigroup: IntSemigroup
	at org.jetbrains.kotlin.codegen.CallBasedArgumentGenerator.generateImplicit(CallBasedArgumentGenerator.java:107)
	at org.jetbrains.kotlin.codegen.ArgumentGenerator.generate(ArgumentGenerator.kt:80)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2459)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2431)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:112)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:101)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.putArgumentOrCapturedToLocalVal(InlineCodegen.kt:331)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.putValueIfNeeded(InlineCodegen.kt:785)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genValueAndPut(InlineCodegen.kt:758)
	at org.jetbrains.kotlin.codegen.CallBasedArgumentGenerator.generateExpression(CallBasedArgumentGenerator.java:62)
	at org.jetbrains.kotlin.codegen.ArgumentGenerator.generate(ArgumentGenerator.kt:65)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2459)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2431)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:67)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:112)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:101)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:376)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:361)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1670)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:84)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:674)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:435)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:266)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:183)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:154)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:196)
	... 39 more

**Comment by truizlop** [comment]
Right now it is a use case that I haven't considered, since the expectation is that `with` applies to a type class parameter. In this case `IntSemigroup` is a concrete instance; therefore, it is not applicable. In any case, we can consider this as a valid use case as long as the type of the parameter is an `extension`.

**Comment by truizlop** [comment]
Proper error reporting is still in our TO-DO list. I've added support for this use case, although I agree with @pakoito that `with` should only be applicable to interfaces with generic parameters.

**Comment by hannespernpeintner** [comment]
Hmm... I don't really understand the reasoning behind this "exception". If I have
```
interface Semigroup<A> {
    fun A.combine(b: A): A
}
extension class IntAddSemigroup: Semigroup<Int> {
    override fun Int.combine(b: Int): Int {
        return this + b
    }
}
extension class IntMultiplySemigroup: Semigroup<Int> {
    override fun Int.combine(b: Int): Int {
        return this * b
    }
}
```

I have the same use case as discussed in the instance resolution thread, where this problem was solved with two extension objects, I think. What is the current agreement of how to solve this? If someone wants to write an add function like above, where he only wants to allow type class instances for addition, does this require another interface that can be type classified somewhere below the SemiGroup interface? Suggestions for this use case are welcome :)

I have the feeling that only allowing interfaces with generic type leads people to circumvent this very limitation with <Any>. Further, allowing only interfaces as type classes makes sense from a definition of type classes point of view, but from the user's point of view, it would be cumbersome to add another set of interfaces in the described use case just to fulfill the requirements.

I hope I'm not getting on your nerves yet :)

* As in _A typeclass is a sort of interface that defines some behavior_

**Comment by truizlop** [comment]
In this case, having two instances of a typeclass for the same type breaks coherence, which basically means *one instance per data type, per typeclass, per codebase*. You can have a "default" one to be resolved automatically (the one marked with `extension`) and pass the other one manually. Otherwise, there is an ambiguity problem and the compiler cannot tell which instance needs to be chosen.

An alternative would be to do something like:

```kotlin
interface Sum<A> : Semigroup<A>
interface Product<A> : Semigroup<A>

extension class IntAddSemigroup : Sum<Int> { ... }
extension class IntProductSemigroup : Product<Int> { ... }
```

And then define your functions like:

```kotlin
fun <A> sumCombine(a: A, b: A, with semigroup: Sum<A>): A = a.combine(b)
fun <A> productCombine(a: A, b: A, with semigroup: Product<A>): A = a.combine(b)
```

Those two functions will be able to properly resolve the corresponding instances.

**Comment by hannespernpeintner** [comment]
Okay, this is what I tried as a workaround already anyway so I think it's an appropriate handling for this case. Thanks for your effort, can be closed I guess :)
